version: '3.9'

services:
  slc_budget_back:
    container_name: slc_budget_back
    build:
      context: ./back
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://slc-budget.cwyblvgboiei.us-east-1.rds.amazonaws.com:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=slc-budget1*

  slc_budget_front:
    container_name: slc_budget_front
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    command: npm run dev
    depends_on:
      - slc_budget_back